apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
    version: "2.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api-server
  template:
    metadata:
      labels:
        app: api-server
        service: api-server
        version: "2.0"
    spec:
      containers:
        - name: api-server
          image: server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
         
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
    service: api-server
    version: "2.0"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: api-server