apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-consumer
  labels:
    app: api-consumer
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api-consumer
  template:
    metadata:
      labels:
        app: api-consumer
        service: api-consumer
        version: "1.0"
    spec:
      containers:
        - name: api-consumer
          image: consumer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
         
---
apiVersion: v1
kind: Service
metadata:
  name: api-consumer
  labels:
    app: api-client
    service: api-consumer
    version: "1.0"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: api-consumer